### ISSUE TITLE
Running on macOS ?

### ISSUE THREAD

**Issue by jrabary** [rail-berkeley/bridge_data_robot#2]
Hi,
Thanks for releasing the bridge data environment. I would like to evaluate it on our own robot but I have a Mac with m1 chip. Since everything is based on docker is it mandatory to install the window x driver on the host ?

**Comment by youliangtan** [comment]
Hi @jrabary, the widowx driver is installed within the docker image, should work out of the box. Also take note that the current base image is a `nvidia/cuda:11.8.0-cudnn8-devel-ubuntu20.04`, thus it technically requires a nvidia GPU.
